### ISSUE TITLE
README would be improved by examples

### ISSUE THREAD

**Issue by robdimsdale** [cppforlife/go-patch#1]
The README currently contains links to the RFCs which is helpful, but hard to parse. An example for each of the supported operations (e.g. patch, remove, etc) with yaml files for each of input, patch, and output would be extremely helpful.

**Comment by cppforlife** [comment]
Covered in https://github.com/cppforlife/go-patch/commit/8542be608b23be2c01efcfc09ff936aee0ffc6b3
